### ISSUE TITLE
qt6ct

### ISSUE THREAD

**Issue by kRHYME7** [RAprogramm/hyprdots-theme#1]
```
❯ Hyprdots theme patch  'One-Dark' 'https://github.com/RAprogramm/hyprdots-theme/tree/One-Dark' 'mskelton.one-dark-theme~One Dark Theme'
Directory /home/khing/Clone/HyprdotsPatch-One-Dark already exists. Using existing directory.
No local changes to save
Already up to date.
/home/khing/Storage/My_Documents/GitHub/Hyprdesk/Scripts

Patching --//One-Dark//-- from /home/khing/Clone/HyprdotsPatch-One-Dark

[OK] .config/hypr/themes/One-Dark.conf
[OK] .config/kitty/themes/One-Dark.conf
[OK] .config/Kvantum/One-Dark/One-Dark.kvconfig
[OK] .config/Kvantum/One-Dark/One-Dark.svg
[OK] .config/qt5ct/colors/One-Dark.conf
[ERROR] .config/qt6ct/colors/One-Dark.conf --> does not exist in /home/khing/Clone/HyprdotsPatch-One-Dark/Configs/
```

Halu, new config dependency fro qt6ct. 

Also better to use the ```  'https://github.com/RAprogramm/hyprdots-theme/tree/One-Dark'  ``` as themepatcher now is broken, the .name element is moved somewhere

Here's a better way to add it 
```
./themepacther.sh  'One-Dark' 'https://github.com/RAprogramm/hyprdots-theme/tree/One-Dark' 'mskelton.one-dark-theme~One Dark Theme'
```

or 
```
 Hyprdots theme patch  'One-Dark' 'https://github.com/RAprogramm/hyprdots-theme/tree/One-Dark' 'mskelton.one-dark-theme~One Dark Theme'
```

**Comment by RAprogramm** [comment]
> ```
> ❯ Hyprdots theme patch  'One-Dark' 'https://github.com/RAprogramm/hyprdots-theme/tree/One-Dark' 'mskelton.one-dark-theme~One Dark Theme'
> Directory /home/khing/Clone/HyprdotsPatch-One-Dark already exists. Using existing directory.
> No local changes to save
> Already up to date.
> /home/khing/Storage/My_Documents/GitHub/Hyprdesk/Scripts
> 
> Patching --//One-Dark//-- from /home/khing/Clone/HyprdotsPatch-One-Dark
> 
> [OK] .config/hypr/themes/One-Dark.conf
> [OK] .config/kitty/themes/One-Dark.conf
> [OK] .config/Kvantum/One-Dark/One-Dark.kvconfig
> [OK] .config/Kvantum/One-Dark/One-Dark.svg
> [OK] .config/qt5ct/colors/One-Dark.conf
> [ERROR] .config/qt6ct/colors/One-Dark.conf --> does not exist in /home/khing/Clone/HyprdotsPatch-One-Dark/Configs/
> ```
> 
> Halu, new config dependency fro qt6ct.
> 
> Also better to use the ` 'https://github.com/RAprogramm/hyprdots-theme/tree/One-Dark' ` as themepatcher now is broken, the .name element is moved somewhere
> 
> Here's a better way to add it
> 
> ```
> ./themepacther.sh  'One-Dark' 'https://github.com/RAprogramm/hyprdots-theme/tree/One-Dark' 'mskelton.one-dark-theme~One Dark Theme'
> ```
> 
> or
> 
> ```
>  Hyprdots theme patch  'One-Dark' 'https://github.com/RAprogramm/hyprdots-theme/tree/One-Dark' 'mskelton.one-dark-theme~One Dark Theme'
> ```

so, i changed url in command.
what i have to do now with this dependencie for qt6? should this be solve by the themepatcher?

**Comment by kRHYME7** [comment]
#944 this should fix it, but yeah it's better to use the branch link as it's straight forward. 

>  what i have to do now with this dependencie for qt6? should this be solve by the themepatcher?

You just need to add those missing file ``` .config/qt6ct/colors/One-Dark.conf ```

**Comment by kRHYME7** [comment]
Patched.

**Comment by RookiexCookie** [comment]
um there is a typo 
make that `./themepatcher.sh`

**Comment by kRHYME7** [comment]
My bad.

**Comment by RookiexCookie** [comment]
yes that one is pretty handy

**Comment by RookiexCookie** [comment]
Looks very good to me with all the other application
whats the problem with dolphin that you wanna change?

**Comment by kRHYME7** [comment]
>  whats the problem with dolphin that you wanna change?

your icons rendered correctly? 

![image](https://github.com/RAprogramm/hyprdots-theme/assets/53417443/e6cdac1c-f1ad-4921-9e82-6f5cca397aae)

**Comment by RAprogramm** [comment]
> Looks very good to me with all the other application whats the problem with dolphin that you wanna change?

![240223_22h55m09s_screenshot](https://github.com/RAprogramm/hyprdots-theme/assets/70325462/bc304164-6aee-4b4b-8d1b-6dda48dd4ef8)

i dont like dolphin background. it is purple little bit, but must be some of grey referense from readme file
