### ISSUE TITLE
Kvantum, Dolphin and Firefox colors

### ISSUE THREAD

**Issue by RAprogramm** [RAprogramm/hyprdots-theme#4]
> Looks very good to me with all the other application whats the problem with dolphin that you wanna change?

![240223_22h55m09s_screenshot](https://github.com/RAprogramm/hyprdots-theme/assets/70325462/bc304164-6aee-4b4b-8d1b-6dda48dd4ef8)

i dont like dolphin background. it is purple little bit, but must be some of grey referense from readme file.

ALSO firefox header must be grey, but it is some kind of dark blue
![240223_23h02m51s_screenshot](https://github.com/RAprogramm/hyprdots-theme/assets/70325462/f578304f-26f4-4a39-826a-fec01844e575)

_Originally posted by @RAprogramm in https://github.com/RAprogramm/hyprdots-theme/issues/1#issuecomment-1961376188_

**Comment by RookiexCookie** [comment]
Oh i see the problem with dolphin
so where does the theme configs at  ? 

also for firefox i use the adaptive tab bar color so i didnt saw that ma bad

**Comment by RookiexCookie** [comment]
Got it 
![image](https://github.com/RAprogramm/hyprdots-theme/assets/136296017/09e26f50-5462-48a8-bb45-ec3c3917459d)
in `/.config/Kvantum/One-Dark/One-Dark.svg` just do find+replace #262335 with #272C33 or any grey color you want
and also change base.color with the desired color in `One-dark.kvconfig` it will be in same directory 

had to track the down color using hyprpicker XD , not very coder like

**Comment by prasanthrangan** [comment]
I'll try to fix the kvantum colors and push it.

**Comment by RAprogramm** [comment]
Thank you so mush!

**Comment by RookiexCookie** [comment]
uh just one problem 
when hovering over the files
![image](https://github.com/RAprogramm/hyprdots-theme/assets/136296017/71bc2783-139b-4156-a548-d9446284dba7)
yea that happens in that hideous color dont know what element is that one rn :(

**Comment by RAprogramm** [comment]
I saw same settings in somewhere kvantum manager...let's try to find it!

**Comment by prasanthrangan** [comment]
Fixed in #6
